In [2]:
import numpy as np

### NumPy Indexing and Slicing of Vectors

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[6]  #Indexing

np.int64(17)

In [6]:
arr[1: 5] #Slicing  

array([12, 13, 14, 15])

In [7]:
arr[:5]  #From 0 to 5

array([11, 12, 13, 14, 15])

In [9]:
arr[5: ]  #From 5 to last element

array([16, 17, 18, 19, 20])

In [11]:
arr_slice = arr[3: :2] #Step of 2
arr_slice

array([14, 16, 18, 20])

### NumPy Indexing and Slicing of Matrix

In [12]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [20]:
row_indexing = arr[0] # Row-wise Indexing
row_indexing

array([1, 2, 3, 4, 5])

In [17]:
arr[0, 4] #Get Single element

np.int64(5)

In [18]:
sliced_matrix = arr[0: 2, 1: 3]
sliced_matrix

array([[2, 3],
       [7, 8]])

matrix = arr[3: , 2: ]
matrix

In [22]:
column_indexing = arr[: , 2]  #Column-wise indexing
column_indexing

array([ 3,  8, 13, 18, 23, 28])

### Boolean Indexing

In [23]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
bool_index = arr % 2 ==0
bool_index

array([ True,  True,  True,  True,  True])

In [29]:
arr = arr[bool_index]  #Removed all the false elements
arr

array([12, 14, 16, 18, 20])