In [2]:
import numpy as np

### Array Operations

#### 1. Arithmetic Operations

In [3]:
a = np.arange(1, 11)
b = np.arange(11, 21)


[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [7]:
addition = a + b  # Addition of two arrays  -- Must have equal elements in both arrays
addition

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [9]:
subtraction = b-a
subtraction

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [10]:
multiplication = a * b
multiplication

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [13]:
division = a / b
division

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ])

In [14]:
exponential = a **b
exponential

array([                  1,                4096,             1594323,
                 268435456,         30517578125,       2821109907456,
           232630513987207,   18014398509481984, 1350851717672992089,
       7766279631452241920])

#### 2. Broadcasting

In [16]:
list = [10,20,30,40,50]
arr = np.array(list)

In [17]:
arr + 10

array([20, 30, 40, 50, 60])

In [19]:
arr = np.arange(1, 26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
arr * 5

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100],
       [105, 110, 115, 120, 125]])

#### 3. Deep Copy And Shallow Copy

In [3]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [6]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [7]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [21]:
shallow = arr.view()  #Shallow Copy
shallow[0] = 99

In [11]:
shallow   

array([99,  2,  3,  4])

In [20]:
arr # Changes in original array

array([99,  2,  3,  4])

In [14]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [16]:
deep = arr1.copy() #Deep Copy
deep[0] = 77

In [17]:
deep

array([77,  2,  3,  4])

In [19]:
arr1  # No Changes in original array

array([1, 2, 3, 4])

#### 4. Matrix Operations

In [23]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [24]:
A

array([[1, 2],
       [3, 4]])

In [25]:
B

array([[5, 6],
       [7, 8]])

In [27]:
A @ B

array([[19, 22],
       [43, 50]])

In [28]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [29]:
A.T

array([[1, 3],
       [2, 4]])

#### 5. Advance Array Manipulation

#### Stacking Array

In [31]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [33]:
vertical_stack = np.vstack((a,b))  #Vertical stack
vertical_stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
horizontal_stack = np.hstack((a, b)) #horizontal stack
horizontal_stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
column_stack = np.column_stack((a, b)) #column stack
column_stack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### Splitting array

In [36]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
horizontal_split = np.hsplit(c, 2)   #Horizontal Split
horizontal_split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [40]:
vertical_split = np.vsplit(c, 4) #Vertical Split
vertical_split

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]