In [2]:
import numpy as np

### Valid Sudoku

In [12]:
 s = np.array([
    [5,3,4, 6,7,8, 9,1,2],
    [6,7,2, 1,9,5, 3,4,8],
    [1,9,8, 3,4,2, 5,6,7],

    [8,5,9, 7,6,1, 4,2,3],
    [4,2,6, 8,5,3, 7,9,1],
    [7,1,3, 9,2,4, 8,5,6],

    [9,6,1, 5,3,7, 2,8,4],
    [2,8,7, 4,1,9, 6,3,5],
    [3,4,5, 2,8,6, 1,7,9]

 ])

In [15]:
a = np.sum(s, axis = 1)

for i in a:
    if i !=45:
        print("Not a valid sudoku")
        break
else:
    print("For rows it is a valid sudoku")

For rows it is a valid sudoku


In [16]:
b = np.sum(s, axis =0)

for i in b:
    if i !=45:
        print("Not a valid sudoku")
        break
else:
    print("For columns it is a valid sudoku")

For rows it is a valid sudoku


In [25]:
slice_1 = s[: 3, : 3]
slice_1

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [22]:
slice_2 = s[:3, 3:6]
slice_2

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [24]:
slice_3 = s[: 3, 6:]
slice_3

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [30]:
for i in range(0, 9, 3):   #In a simpler way

    for j in range(0, 9, 3):
        n = s[i: i+3, j: j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


### General Questions

In [49]:
import numpy as np

#Columns : [Age, Maths Marks, Science Marks]

data = np.array([

    [18, 85, 78],
    [19, 92, 88],
    [17, 76, 95],
    [18, 65, 70],
    [20, 91, 85]
])

In [35]:
#Get Shape of the matrix

data.shape

(5, 3)

In [37]:
#Find the average age of students
avg = np.mean(data[: , 0])
avg

np.float64(18.4)

In [38]:
# Find the average of students in maths
maths_avg = np.mean(data[ :, 1])
maths_avg


np.float64(81.6)

In [52]:
#Extract maths marks of all students

maths = data[:, 1]
maths

array([85, 92, 76, 65, 91])

In [41]:
#Find the highest Science mark

high_science = np.max(data[:, 2])
high_science

np.int64(95)

In [50]:
# Get details of the student who scored more than 90 in Maths

data[data[:, 1] > 90]



array([[19, 92, 88],
       [20, 91, 85]])

In [54]:
#Increase maths marks of all students by 5

maths + 5

array([90, 97, 81, 70, 96])

In [56]:
#Find how many students are younger than 19

age = data[:, 0] < 19
age

array([ True, False,  True,  True, False])

In [58]:
len(data[data[:, 0] < 19])

3

In [66]:
#Calculate the average marks in each subject (column-wise meana)

np.mean(data[:, 1:], axis =0)


array([81.8, 83.2])

In [71]:
#Get data of students who scored at least 80 in both subjectsa

data[ (data[: , 1] >=80) & (data[:, 2] >=80) ]


array([[19, 92, 88],
       [20, 91, 85]])

In [75]:
#Replace all science marks <75 with 0

data[:, 2] [data[:, 2] < 75 ] =0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 91, 85]])

0